### ISSUE TITLE
Visualization doesnot show abstract Rules

### ISSUE THREAD

**Issue by SchroedingersCatIsUndead** [eMoflon/emoflon-issues#783]
If you write an abstract rule, it won't be drawn by PlantUML

**Comment by anthonyanjorin** [comment]
There is now a view menu with an action that you can use to toggle between visualising the actual rules (so with abstracts and refinements), or the resulting and final TGG (no abstract rules and flattened refinements).  Please try to toggle this and see if the problem goes away.

**Comment by anthonyanjorin** [comment]
There is already an issue #770 to improve the action and menu.

**Comment by SchroedingersCatIsUndead** [comment]
oh, I see, but if I use this button, I will only see the TGGObject which are discribed in the Rule without refinements. I wanted to see an abstract rule with refinments. I think it's not a Bug it's a feature Request now.

**Comment by SchroedingersCatIsUndead** [comment]
So I have added this new feature. It's working with flatten refinements button as well as the other view.
